### ISSUE TITLE
✨ Docusaurus docs site

### ISSUE THREAD

**Issue by TylerGillson** [validator-labs/validator#389]
### Summary

Create a Docusaurus site inside a new repo: `validator-labs/docs`.

**Comment by mattwelke** [comment]
[Site](https://validator-labs.github.io/docs/) is online. We will add content over the next week or so. Goal for now is to document how to use `validatorctl` and give people an overview of the project and its architecture (e.g. how plugins come into play).

**Comment by mattwelke** [comment]
Docs content is now published.
